### ISSUE TITLE
error on unused eslint directives

### ISSUE THREAD

**Issue by ndhoule** [goodeggs/eslint-plugin-goodeggs#216]
We enable this check in `goodeggs-toolkit` by passing `--report-unused-disable-directives` to `eslint`, but enabling this rule via configuration is preferable.

https://mysticatea.github.io/eslint-plugin-eslint-comments/rules/no-unused-disable.html

**Comment by serhalp** [comment]
Current setup seems fine, since we should only use goodeggs-toolkit 🤷🏼
