### ISSUE TITLE
Ban use of primitive boxed types (String, Boolean, Number)

### ISSUE THREAD

**Issue by serhalp** [goodeggs/eslint-plugin-goodeggs#468]
We should:
- enable this rule: https://eslint.org/docs/rules/no-new-wrappers
- enable this rule, specifically banning `String`, `Boolean`, and `Number` types: https://github.com/typescript-eslint/typescript-eslint/blob/3764248084455409f085c5bc4706079405cef618/packages/eslint-plugin/docs/rules/ban-types.md

There are absolutely no reasons to use those classes rather than the regular JS primitives. There are many ways to shoot yourself in the foot if you do use them.

It's very easy to write a TS type with `Boolean` instead of `boolean` and not realize what you're permitting.

I don't think this is worth a best-practices Issue, since this is just enabling rules to prevent code that is 100% a mistake, and we don't currently intentionally use these.

**Comment by mattpetrie** [comment]
@serhalp `ban-types` should be enabled by default when we make the upgrade to typescript-eslint in this PR: https://github.com/goodeggs/eslint-plugin-goodeggs/pull/462/

**Comment by mattpetrie** [comment]
It also looks like `no-new-wrappers` is already enabled. (just tested it out in Garbanzo).

**Comment by serhalp** [comment]
Good catch @mattpetrie! However, I did a little digging and I can't seem to convince myself that it's true that `String`, `Boolean`, `Number` types will be banned be default in the `@typescript-eslint/eslint-plugin/recommended` ruleset in v3 but wasn't in v2. As best I can tell, it should already have been banned by default in v2, so if we're have a bunch in garbanzo, we must have something misconfigured? 🙃 

v3 added `Function` to the default bans and a few other things: https://github.com/typescript-eslint/typescript-eslint/pull/848. It already had `String`, etc.

**Comment by mattpetrie** [comment]
> As best I can tell, it should already have been banned by default in v2, so if we have a bunch in garbanzo, we must have something misconfigured? 🙃

Hmm, yeah something is fishy here and warrants further investigation. It does seem that something is misconfigured. When I try typing something as `String` in Garbanzo, I do get the expected error feedback in VSCode, but I don't get the error when running `yarn typecheck`. Weird. 🤔
